### ISSUE TITLE
Mods not opening in Hedgemodmanager

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#159]
## Describe the issue/bug

When i try to open a file to load in a mod to use, it doesnt work.
## Expected Behaviour

I expected it to just do everything fine but it didnt.
## Additional Context

Sometimes it works but it isnt working on this one mod i got.

**Comment by ghost** [comment]
plz help

**Comment by thesupersonic16** [comment]
Please include more information. Like what mod you are trying to load and its version and how you tried to get it to work.

**Comment by ghost** [comment]
Im trying to use a shadow the hedgehog model in sonic lost world. I keep clicking install from folder or archive and it doesnt install the mod.

**Comment by thesupersonic16** [comment]
Can you please send a link to the mod?

**Comment by ghost** [comment]
https://www.mediafire.com/file/3bsu308k913pfdz/Shadow_Mod.zip/file

https://www.mediafire.com/file/bljx3a9w1wrolwd/Shadow_Mod_No_Music.zip/file

**Comment by ghost** [comment]
so how do i fix this

**Comment by thesupersonic16** [comment]
The mod doesn't contain a mod.ini file which is required to install the mod. You can either make one yourself or contact the mod author to make one for the mod.

Since this isn't a HMM issue I'm going to close this issue. If you do run into any issues installing the mod with a mod.ini included in the zip feel free to reopen this issue.

**Comment by ghost** [comment]
i dont know how to install the mod.ini

**Comment by thesupersonic16** [comment]
It just needs to be in the mod folder with the disk folder. mod.ini just describes the information about the mod.
