### ISSUE TITLE
HedgeModManager.exe was blocked because it could harm your device.

### ISSUE THREAD

**Issue by Duncan23112** [thesupersonic16/HedgeModManager#177]
Hi, I'm new to GitHub. I just downloaded the HedgeModManager, and I recieved an error message stating that it might potentially harm my PC.

**Comment by Sajidur78** [comment]
It's most likely a false positive, there's nothing we can do about it. If you're worried about using it then re-download from the following link. https://github.com/thesupersonic16/HedgeModManager/releases/download/7.2-9/HedgeModManager.exe

**Comment by thesupersonic16** [comment]
To add to this. HedgeModManager is unsigned due to a limitation of how it works. If its a SmartScreen warning, it is just telling you the file is unsigned. Aslong you download HedgeModManager from it's [Releases page](https://github.com/thesupersonic16/HedgeModManager/releases) or from the [GameBanana page](https://gamebanana.com/tools/6311). Once your sure, just run it and click "More Info" and a new button should appear on the bottom that says "Run Anyway", just click that.
