### ISSUE TITLE
Startup Issue (Forces)

### ISSUE THREAD

**Issue by notspin** [thesupersonic16/HedgeModManager#38]
![screenshot_145](https://user-images.githubusercontent.com/47406282/52385854-77ac2a00-2a51-11e9-8215-4307f3cc4ea3.png)

Currently having an crash with booting the mod manager properly. I loaded the mods, and the game refuses to start. I opened the console up to see the reason and I see this being "loaded in reverse". Is this normal?

**Comment by thesupersonic16** [comment]
This issue seems common for people who got the "Forces got an update on Steam issue".

Possible Solution is wiping HMM using this batch file.

To use the batch file:
 1. You must close HMM and Forces and wait for a bit.
 2. Place the bat file into your exec folder
 3. Run the Bat file
 4. Download HMM again
 5. Install HMM
 6. Copy each mod you want to play from the mods.old folder into the mods folder. (Do not copy or rename the whole folder)

Download: [Uninstall HMM.zip](https://github.com/thesupersonic16/HedgeModManager/files/2839415/Uninstall.HMM.zip)

**Comment by notspin** [comment]
It has worked for me, thanks!
Been a year since i replied; i just found out i had a github account lol

**Comment by thesupersonic16** [comment]
Great to see that the issue has been resolved. Closing...
