### ISSUE TITLE
[Bug] It just..doesn't want to open. I double click the application, and wait for a few minutes. I even looked in Task Manager and when I opened it again, I saw it running for a few seconds but then it just closed down

### ISSUE THREAD

**Issue by Vcl185** [thesupersonic16/HedgeModManager#452]

**Comment by Rachel8260** [comment]
Same issue here, still no fixes i can find.

**Comment by thesupersonic16** [comment]
Please use the template correctly and provide some more information like where you downloaded the exe, where you ran it and what game launchers you have.

Since you mentioned the application closing after a few seconds, try making sure [.NET Framework 4.7.2](https://go.microsoft.com/fwlink/?linkid=863265) is installed and if it continues to crash, check for any files that starts with 
`HedgeModManager` within `%localappdata%\CrashDumps` and zip the newest one and upload it here or DM the file to me on Discord at `SuperSonic16#0001`.

**Comment by Rachel8260** [comment]
i see crash dumps for Sonic Generations, but nothing for HedgheModManager. I got Hedgemod manager straight from here and ran it in the default install directory.
