### ISSUE TITLE
[Bug] ORIGINS: "Enable Lives in Anniversary Mode" code doesn't work with Sonic 3.

### ISSUE THREAD

**Issue by GeekCritique** [thesupersonic16/HedgeModManager#463]
## Describe the issue/bug
Since the patch several weeks ago, "Enable Lives in Anniversary Mode" doesn't affect Sonic 3. The game continues to use the COINS system instead.

**Comment by DeaTh-G** [comment]
Yeah, sadly this is something the newest Origins patch broke and I'm not even sure why. The sad reality is that with Origins' patch not fixing the issue on systems that include a unicode character in their Windows user name, like mine, I can't really be motivated to work on a game that I can't even launch without external modifications to begin with. Love me some $40 digital paperweight.

The bug affects both this and the Mirror Mode version of the code, I know that much and is caused by the following offsets being wrong since the update. I tried to look into it on the update's launch but I lost all motivation for working on anything Origins related.

I know the rsdkGlobals value is still found by the Signature Scan I'm doing for it, so it has to be something they broke with the offsets in this following picture:
![S3&K code section](https://user-images.githubusercontent.com/55578911/186887230-21d0ef16-3510-40a1-8847-e854fa0aba10.png)

My two suggestions to anyone looking at this that:
A) The code can be reworded to say only for RSDKv3 and RSDKv4 games
B) Somehow find out the proper offsets for the globals in the newest patch.

As said for the reasons above, I'm not personally motivated anymore to work on the patch but I'll try to reach out to some people in the REMS discord server and see if there's something that could be done about this.

**Comment by DeaTh-G** [comment]
Well that got fixed in #464 much sooner than I expected at the time of sending the message.
However that's all thanks to @Rubberduckycooly and I'm claiming nothing over this fix.

Updating your community codes should now result in both the Mirror Mode and Anniversary Mode lives code working again on the latest update.
