### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TW1302** [thesupersonic16/HedgeModManager#543]
My mods are not loading up it runs vanilla sonic generations instead and I’m on steam deck

**Comment by sonic2kk** [comment]
Is the modloader installed? Under the "Settings" tab you'll see these three buttons. If one of them says "Install Mod Loader" then the modloader is probably not installed.

![image](https://user-images.githubusercontent.com/7917345/209448106-d35c5671-2130-43a8-bde7-84be65294337.png)

**Comment by TW1302** [comment]
Yeah it's installed this started happening when I put sonic generations and my mods on my SD card

**Comment by sonic2kk** [comment]
Did you reinstall your mods after moving them as well as the modloader?

Generally when modding games you won't want to move them.

**Comment by TW1302** [comment]
Yeah when I moved sonic generations to the SD card somehow my mods got deleted so I had to re-download them and I don't know about mod loader where is it in the files oh and my codes don't work either anymore

**Comment by sonic2kk** [comment]
Make sure the path in HMM is definitely pointing to the right Sonic Generations install (probably something like `Z:\run\media\<blah>\steamapps\common\Sonic Generations`). If it is pointing to a path that looks like a valid Linux mount path, go to the settings tab and click "Uninstall mod loader" and then click it again to reinstall the modloader. If it's not pointing to this path and is pointing to somewhere on your home folder, you'll want to update the path to the installation folder on your microSD card.

I would guess maybe some of the HMM paths haven't updated and so the modloader isn't installed. You might still have a Sonic Generations install folder on your main SSD's library folder at `/home/deck/.local/share/Steam/steamapps/common/Sonic Generations` (and HMM may still be pointing to this path), since Steam usually doesn't remove third-party files. HMM may still be looking at this and expecting it to be the Sonic Generations install folder, particularly if the modloader is still installed there.

**Comment by TW1302** [comment]
Thank you so much it's working again

**Comment by sonic2kk** [comment]
No worries, this is just a thing you'll have to do if you move your game (probably on Windows too I would guess but not 100% sure)

You can probably close this issue if it's fixed now :-)
