### ISSUE TITLE
[Bug] installed Mod loder for sonic froniters the game won't launch anymore

### ISSUE THREAD

**Issue by Paper-Crusader** [thesupersonic16/HedgeModManager#560]
## Describe the issue/bug

after i installed Mod loder for sonic froniters the game won't launch anymore i have tried uninstalling the mod loader and the game works fine
## Expected Behaviour

To run the codes
## Additional Context

this isn't happening for any other games such as generations or lost world im on windows btw

**Comment by thesupersonic16** [comment]
Thanks for letting us know about the issue. Within our testing we have not noticed any issues, but have heard from others that the update is nolonger working. We have decided to pull the update and Hedge Mod Manager should now download the previous build. Can you confirm if it is still having issues?

**Comment by Buckethat267** [comment]
Hello, I’ve been having this same issue on my steam deck. I used the old bottles method because the Steam Tinker Launch didn’t work for me. Now I got HMM to run but whenever I install the mod loader the game doesn’t launch. But when I uninstall the mod loader it works fine. And I tested the mod loader without using any mods or codes, the game still wouldn’t work. 

I’m using the latest version of HMM (7.9). I tried going back to a previous version to see if it would work then but no other version supports Sonic Frontiers (at least to my knowledge). And when I switch to development it just brings me back to the latest version and I have the same problem. Is there perhaps a different version that I’m not seeing that I could use, or is there something else I could do?

**Comment by thesupersonic16** [comment]
> Hello, I’ve been having this same issue on my steam deck. I used the old bottles method because the Steam Tinker Launch didn’t work for me. Now I got HMM to run but whenever I install the mod loader the game doesn’t launch. But when I uninstall the mod loader it works fine. And I tested the mod loader without using any mods or codes, the game still wouldn’t work.
> 
> I’m using the latest version of HMM (7.9). I tried going back to a previous version to see if it would work then but no other version supports Sonic Frontiers (at least to my knowledge). And when I switch to development it just brings me back to the latest version and I have the same problem. Is there perhaps a different version that I’m not seeing that I could use, or is there something else I could do?

This is unrelated to this issue. Please move to #219 as your issue is the game crashing due to an compatibility with mono and the 64-bit modloaders on Linux, you will need to install dotnet48 on each 64-bit game prefix.
