### ISSUE TITLE
HMM not showing up on Steam Deck

### ISSUE THREAD

**Issue by martinsaenz96** [thesupersonic16/HedgeModManager#563]
I've been planning on modding "Sonic Frontiers" and eventually "Sonic Origins" on my Steam Deck. I followed this [tutorial ](https://youtu.be/66B9K-wSqTo) on getting HMM to run on the Steam Deck.

I did everything I was told and HMM is already installed, butb it just will not open. I typed "./steamtinkerlaunch hmm start" within konsole and it never works. Even manually double clicking doesn't work either.

Am I doing something wrong? If so, then what's the solution to the problem?

**Comment by Joefers** [comment]
Howdy!

I finally got this running on Steam Deck yesterday. Here's some tips:

**WARNING**: Denuvo (anti-piracy software) will LOCK YOU OUT of Frontiers for 24 hours if you swap the Proton versions in Frontiers' Compatibility tab more than 5 times! This is because it considers prefix changing to be a 'hardware change' (since you're basically creating a new Windows OS in each prefix). This happened to me a few days ago getting this together. BE CAREFUL!

If HedgeModManager doesn't launch (even after saying it's being Started), it's not loading most likely due to not having dotnet40/48 installed for HMM's prefix (not Frontiers' prefix).

You still need to get HMM running, so the video's guide should get you there -- don't skip the parts about using proton5.0-10-b via the STL Global menu; then switch to GE-Proton7-43 for HMM after that bit's done. If all else fails, you may need to delete the HMM files found in '~/.config/steamtinkerlaunch' to get rid of HMM's prefix and start over.

I would say this annoying effort's been worth it, since I can install the Simple Foliage mod and the No Shadows code for better FPS on the deck. Runs great!

Good luck!
