### ISSUE TITLE
Frontiers Crashing on Startup When Twitch Studio is Active

### ISSUE THREAD

**Issue by dqf318** [thesupersonic16/HedgeModManager#588]
For some reason, when I stream on Twitch, the game crashes on startup when I have the Mod Loader installed.  Interestingly, it works fine when I'm not streaming, or when it's not showing gameplay on the screen.  I have tried disabling the save file redirection, but that didn't work at all.  It's also worth noting that it even crashes when I just have Twitch Studio open on Gameplay.  I even made sure that only Twitch Studio and the game are the only items open and it still crashes.  Here's my PC specs for reference:
Device:
Device name DESKTOP-25PBLI2

Processor AMD Ryzen 7 5700G with Radeon Graphics            3.80 GHz

Installed RAM 16.0 GB (15.8 GB usable)

Device ID F6161D41-F1A8-4D52-AE94-E9CF88DF11CA

Product ID 00342-20765-61953-AAOEM

System type 64-bit operating system, x64-based processor

Pen and touch No pen or touch input is available for this display

Windows:
Edition Windows 11 Home

Version 22H2

Installed on ‎10/‎1/‎2022

OS build 22621.1105

Serial number MJ0GG5D4

Experience Windows Feature Experience Pack 1000.22638.1000.0

Any idea why this is the case?

**Comment by thesupersonic16** [comment]
I dont use Twitch Studio, but from what I am hearing, your streaming software may be attempting to hook into the game, then crashing. Maybe try look for any hooking options and try disabling that and try again.

If you have any crash dumps, please send one.

**Comment by dqf318** [comment]
> I dont use Twitch Studio, but from what I am hearing, your streaming software may be attempting to hook into the game, then crashing. Maybe try look for any hooking options and try disabling that and try again.
> 
> If you have any crash dumps, please send one.

Well, it's the game that's crashing, not the streaming software itself.  As for crash dumps, how would I go about getting them?

**Comment by thesupersonic16** [comment]
If `%localappdata%\CrashDumps` exists, it should be in there with the name of the exe that crashed.

**Comment by dqf318** [comment]
Huh, looks like there isn't a crash dump given when it happens.

**Comment by dqf318** [comment]
Found an interesting revelation.  Apparently, it only crashes when I have the main screen share set to Fullscreen Application.  If I instead set it to Entire Screen, it works as intended.

**Comment by AskaLangly** [comment]
May I? 
 
I had _Sonic Frontiers_ version 1.20 crash on me when attempting to hook to Discord. I don't think the codes or loader are doing it, it's more like any other software running in the background. I have MSI Afterburner and RivaTuner installed; can you confirm that you have those installed and running as well? I'm asking because I noticed a trend in games crashing when attempting to hook to Discord; examples include _Like a Dragon: Ishin!_ and _Neptunia: Sisters vs Sisters_. 
 
I understand that you're talking about Twitch Studio, but it does involve hooking to other software. What I've been doing to circumvent this is to hook Discord to OBS's Fullscreen Preview, in which my scene is just my first display (the display Frontiers is running on). As long as the preview is not minimized (i.e. behind the game), you should be able to stream with no issues.

**Comment by thesupersonic16** [comment]
Please send a crash dump if you can, so I can get a rough idea what's happening.
