### ISSUE TITLE
Sonic Generations not launching

### ISSUE THREAD

**Issue by throwaway1908** [thesupersonic16/HedgeModManager#61]
Hi. I am having trouble with HedgeModManager after the latest update. I am able to launch the game for a second, but as soon as the game starts up, it closes with no error message whatsoever. Not sure if it's an issue related on my end or if it's something wrong with the mod manager itself.
By the way, it does this even when no mods are selected from the manager.

**Comment by thesupersonic16** [comment]
Can you try deleting the Codes.dat file then running the game directly from Steam(Not through HMM) to see so we can check if the issue is related to GCL's code handler itself or it being something else.
If this does not solve the issue then can you send your `cpkredir.ini` and `ModsDb.ini` in a zip so I can see if there are anything in there that could have caused the issue.

**Comment by throwaway1908** [comment]
Deleted codes.dat, ran Sonic Generations through Steam and it launched just fine.
