### ISSUE TITLE
[Request] Sonic Superstars Support

### ISSUE THREAD

**Issue by thatsmytrunks** [thesupersonic16/HedgeModManager#782]
HedgeModManager has been an absolute treasure for PC releases of Sonic games, and with the release of Sonic Superstars it'd be fantastic if HMM could be the home for a currently splintered Mod scene. Currently folks are using Concursus and BepInEx to load mods for Unity into SuperStars, but the process is messy and documentation is confusing and often conflicting. The tool y'all have made would be a great asset for a game that has a lot of modding potential, and if it's feasible, I hope you'll consider it.

**Comment by Sajidur78** [comment]
Thanks for the compliments! It's very appreciated. However, as of right now superstars support is out of scope for HMM. I'm open to contributions on the matter but we don't really have time for it right now since it's a whole different set of tech stack we aren't very familiar with. Maybe that can change in the future🤞
