### ISSUE TITLE
[Bug] Project Unleashed when I try to load in to windmill isles it crashes. The gpu is a nivdia gtx 1030.

### ISSUE THREAD

**Issue by Mrgeba12** [thesupersonic16/HedgeModManager#808]

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
I can't really provide much help on this issue as this is either an issue with the mod or HE1ML which both I never worked on.

Since the mod is old enough to be created for SonicGMI, I would check with that to see if it works any different, just make sure to uninstall the modloader in HMM before installing SonicGMI.
