### ISSUE TITLE
[Bug] [Sonic Frontiers] [Steam deck] Steamtinkerlaunch "Unhandled exception"

### ISSUE THREAD

**Issue by dawghouse2005** [thesupersonic16/HedgeModManager#843]
So basically every time i try to run HMM though STL this error about wine always comes up? idk what any of this means or what to do. ive been trying since December to get HMM working on my deck and i would greatly appreciate the help
![Screenshot_20240204_200225](https://github.com/thesupersonic16/HedgeModManager/assets/158853380/066eaced-27ff-4cb8-91dd-447abc7a2665)

**Comment by thesupersonic16** [comment]
Hedge Mod Manager currently runs on WPF which is not supported on Mono which is what you are using. You must have .NET Framework 4.8 installed to run this app.

Also since this is an issue with running Hedge Mod Manager on Linux, please move to #219. Remember we do have a guide for running in Bottles in the Wiki tab that may work, if not, feel free to ask in #219 as some others there have gotten the app running.

**Comment by dawghouse2005** [comment]
sorry i didn't put this in the right place. however I installed the framework but it didn't work, idk what i did wrong
