### ISSUE TITLE
Forces Code Loader crashes Sonic Forces 

### ISSUE THREAD

**Issue by frozenLake** [thesupersonic16/HedgeModManager#9]
The game crashes upon launch, so It does not appear to be anything in game. This only happens when the codeloader is installed, otherwise HedgeModManager boots the game just fine. I don't know what causes this.

**Comment by Fighterbuilder** [comment]
I have this same issue. Additionally, the window title is set to "wars" instead of "SONIC FORCES". I copied the output in the output window into a text file attached to this comment.
[launchlog_hedgemodmanager.txt](https://github.com/thesupersonic16/HedgeModManager/files/1486024/launchlog_hedgemodmanager.txt)

**Comment by thesupersonic16** [comment]
Its normal for the title to be "wars", It changes so fast that you wouldn't notice. I'll take a look at this issue, As I heard of more people having this issue.

**Comment by thesupersonic16** [comment]
One issue I have found is that the game crashes when it tries to load an empty archive generated by HedgeModManager, I'll try fix this in the next release.

**Comment by thesupersonic16** [comment]
Please test this build and Reply letting me know if its fixed or not.

https://ci.appveyor.com/project/thesupersonic16/slw-mod-loader

**Comment by frozenLake** [comment]
Codes function without problem now. (as long as you remember to update them)

**Comment by Fighterbuilder** [comment]
Cool, I'll check it out when I get home.
