### ISSUE TITLE
7.12.8 by instance ... 7.13.1 one instance & game selection !?!

### ISSUE THREAD

**Issue by Klemci** [thesupersonic16/HedgeModManager#984]
Hello, i always use one modloader instance (copy) by game, then updating from 7.12.8 to 7.13.1 i discovered it changed, now we have to select game entry at bottom, each time the modloader is started and from any directory it saves the last game selected...

First:
IDK where the settings are written (the games list)...

Twice:
the good behavior is like dgVoodoo2, the (instances) list written in appdata but each modloader EXE instance starts with the corect game selected (the one in the folder, logic) and not user has to DIY (it's an exemple for you next versions and how it could handle that).

Third:
Until it's like that i won't upgrade post 7.12.8 (or .9 btw)

Fork:
Thanks for all and happy new year and all.

**Comment by thesupersonic16** [comment]
We have always discouraged the use of having multiple copies of Hedge Mod Manager and placing them in game folders. I probably should have given some warning for existing users.
In 7.13 we have made major changes with how game detection and selection works to support SxSG which the behaviour you are asking will not work with. I could add it back in for other games, but that is not my priority.
If your issue is your games not being detected, please mention it.

If it helps, you can make shortcuts and pass `--game SonicGenerations` as an argument to auto select games. This will also mean you only need to update one copy of HMM.

**Comment by Klemci** [comment]
OKay, no problemo :) 

Yes, the modmanager doesn't detects the game when used like i do, placed in each game's folder... i don't like single instance, but that's me and my old habits, don't worry.

Thanks for all.
